
env:
  global:
  - REPO_DIR=.
  - TEST_DEPENDS="tox"
  - PLAT=x86_64
  - UNICODE_WIDTH=32
  - TWINE_USERNAME="anthrotype"
  - secure: DNomOm8Gxq0py+fkmTmcQE7bo0WlpGQXL5xnwIHD3CnaPWTRcnbjCHLwxX1IHSXgLsNgSzV3cs4YtwoHdaWbBCozDsqSyG16pvSlCkTEDDz62vWHzlghKjbsY8TCzpc0nK4fJUv1/rUI+CjMtt8rsUh995oDQg6fruArZhuGAmLfdQIRelUpkqTME9jsMav6DzL/W9ZfnZa2srzBYXIrNTPlsHpWdLOaAkhRjtjujguSHsZztwcW+qAWhJYbtAoR6/YF5aB+IxfT/z2G6Zyq/cEwSgXeh1S95FHWE/6Eieh9ZIFYGctlSGKMH3kFGkMZ65UH2qI8I4d0UhSBp+RgA8ScmIycJC53ybJYpB0BHEDmzfk8+VCpTvXvZOyqsJcV/1wmCJV4vdMgAq2zSUOs/qlT/cpfdBvts/GW3FCA2CI/pu1pDtlY2DUS/35nAEaaGTZKoW0Rc1c5tnqMM/LRRo6jQ23FI/J2sdwPQUldlKfncZxSP9SIKm3r7UhJYvFAVurM/7jqM9oS1hI0bzP4fhHvGvD4L6auJNw/HaKscsWpXlFEXnQaTLRhu/9vscveGCyuCSBK3+ITUys/MDu1JD+2J5231zpwAB9dBeGrQ8WRsY+52cWfz13GCefTQ29bmxYOxpii+Fmb44pBvq8NEGghsV6sU7AP0Yo0KLMXXa8=
language: generic
dist: xenial
services: docker
matrix:
  include:
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.6
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.7
    - BUILD_SDIST=true
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.8
  - os: osx
    env:
    - MB_PYTHON_VERSION=3.6
  - os: osx
    env:
    - MB_PYTHON_VERSION=3.7
  - os: osx
    env:
    - MB_PYTHON_VERSION=3.8
before_install:
- source multibuild/common_utils.sh
- source multibuild/travis_steps.sh
- before_install
install:
- build_wheel $REPO_DIR $PLAT
script:
- install_run $PLAT
after_success:
- |
  if [ -n "$TRAVIS_TAG" ] && [ "$TRAVIS_REPO_SLUG" == "googlefonts/compreffor" ]; then
    pip install --upgrade pip
    pip install --upgrade twine
    twine upload wheelhouse/*.whl
    if [ "$BUILD_SDIST" == true ]; then
      pip install --upgrade cython setuptools
      python setup.py sdist
      twine upload dist/*.zip
    fi
  fi
